# Generated by Django 4.0.4 on 2022-05-06 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("records", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="number_of_concurrent_holds",
            field=models.IntegerField(
                blank=True,
                help_text="How many of this item type can be placed on hold at the same time?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="number_of_allowed_renews",
            field=models.IntegerField(
                blank=True,
                help_text="How many times can this item type be renewed?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="number_of_concurrent_checkouts",
            field=models.IntegerField(
                blank=True,
                help_text="How many of this item type can be checked out at the same time?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="number_of_days_per_checkout",
            field=models.IntegerField(
                blank=True,
                help_text="How many days can this item type be checked out for?",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "model__in": ("branchlocation", "alexandriauser")
                        },
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                ("items", models.ManyToManyField(to="records.item")),
                (
                    "session_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
