# Generated by Django 4.0.4 on 2022-05-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_itemtype_number_of_concurrent_holds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemtype",
            name="icon_svg",
            field=models.TextField(
                blank=True,
                help_text='Don\'t have a matching option in the Material Design icons? Copy the full SVG html here to display that instead. WARNING: must be fully formed SVG element; it will not be saved otherwise. Make sure that your `path` tag has `fill="currentColor"` in it so that colors work correctly and ensure that it displays well at 36px by 36px.',
                null=True,
                verbose_name="icon svg",
            ),
        ),
    ]
