# Generated by Django 4.0.1 on 2022-01-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_collection_created_at_collection_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hold",
            old_name="placed_by",
            new_name="placed_for",
        ),
        migrations.AddField(
            model_name="hold",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="notes"),
        ),
    ]
