# Generated by Django 4.0.4 on 2022-05-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_alter_itemtype_icon_svg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemtype",
            name="number_of_allowed_renews",
            field=models.IntegerField(
                default=5, help_text="How many times can this item type be renewed?"
            ),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="number_of_concurrent_checkouts",
            field=models.IntegerField(
                default=100,
                help_text="How many of this item type can be checked out at the same time?",
            ),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="number_of_concurrent_holds",
            field=models.IntegerField(
                default=25,
                help_text="How many of this item type can be placed on hold at the same time?",
            ),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="number_of_days_per_checkout",
            field=models.IntegerField(
                default=21,
                help_text="How many days can this item type be checked out for?",
            ),
        ),
    ]
