# Generated by Django 4.0.4 on 2022-05-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0005_alter_itemtype_number_of_allowed_renews_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="object_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="object_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
