# Generated by Django 4.0.2 on 2022-04-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0007_activate_trigram_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="searchable_authors",
            field=models.CharField(
                blank=True, db_index=True, max_length=800, null=True
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="searchable_subtitle",
            field=models.CharField(
                blank=True, db_index=True, max_length=26021, null=True
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="searchable_title",
            field=models.CharField(db_index=True, max_length=26021),
        ),
        migrations.AlterField(
            model_name="record",
            name="searchable_uniform_title",
            field=models.CharField(
                blank=True, db_index=True, max_length=26021, null=True
            ),
        ),
    ]
