# Generated by Django 6.0 on 2025-12-31 20:24

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("distributed", "0002_alter_setting_name"),
        (
            "records",
            "0008_alter_bibliographiclevel_host_alter_collection_host_and_more",
        ),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="record",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=[
                    "searchable_authors",
                    "searchable_title",
                    "searchable_uniform_title",
                    "searchable_subtitle",
                ],
                name="rcrd_combined_gin_idx",
                opclasses=[
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["searchable_authors"],
                name="sbl_author_rcrd_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["searchable_title"],
                name="sbl_title_rcrd_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["searchable_uniform_title"],
                name="sbl_unfrm_rcrd_title_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="record",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["searchable_subtitle"],
                name="sbl_subtitle_rcrd_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["searchable_name"],
                name="sbl_name_subject_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
