# Generated by Django 4.0.2 on 2022-04-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_record_searchable_title_alter_record_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='searchable_name',
            field=models.CharField(db_index=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
