# Generated by Django 4.0.5 on 2022-06-13 02:52

import alexandria.distributed.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=253)),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.TextField()),
                (
                    "host",
                    models.ForeignKey(
                        default=alexandria.distributed.models.Domain.get_default_pk,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="distributed.domain",
                    ),
                ),
            ],
        ),
    ]
