# Generated by Django 4.0.5 on 2022-06-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="name",
            field=models.CharField(
                choices=[
                    ("name", "Library system name"),
                    ("url", "Library system base URL"),
                    ("ad_1", "Address: street 1"),
                    ("ad_2", "Address: street 2"),
                    ("city", "Address: city"),
                    ("stat", "Address: state (two letter version, like IN or NY)"),
                    ("cntr", "Address: country"),
                    ("zip", "Address: zip code"),
                    ("phon", "Phone number"),
                    ("ebsm", "Enable keeping track of saved money through borrowing"),
                    ("flot", "Floating collection"),
                    ("fucn", "Force unique call numbers"),
                    ("ist", "a,an,the"),
                    ("zurl", "Zenodotus API URL"),
                    ("z_au", "Enable automatic uploads to Zenodotus"),
                    ("z_up", "Automatically check Zenodotus for record updates"),
                    (
                        "d_st",
                        "Default address for new users: state or region (two letter version, like IN or NY)",
                    ),
                    ("d_ct", "Default address for new users: city"),
                    ("d_zc", "Default address for new users: zip code"),
                    ("d_cy", "Default address for new users: country"),
                    ("drpp", "Default number of results per page"),
                    ("dmr", "Default maximum number of renewals"),
                    ("dcdd", "Default checkout duration (days)"),
                    ("d_li", "Default location ID"),
                    (
                        "drdd",
                        "Default renewal delay (how long before an item is due that the renewal button can be pressed) in days",
                    ),
                    ("dhed", "How long to leave a hold on the shelf before it expires"),
                    ("n1t", "Navbar item 1: title"),
                    ("n1u", "Navbar item 1: URL"),
                    ("n2t", "Navbar item 2: title"),
                    ("n2u", "Navbar item 2: URL"),
                    ("n3t", "Navbar item 3: title"),
                    ("n3u", "Navbar item 3: URL"),
                    (
                        "eocd",
                        "Enable automatic downloading of missing cover images from OpenLibrary",
                    ),
                    (
                        "uscc",
                        "When checking in books, have items default to the shelving cart",
                    ),
                    (
                        "scdh",
                        "When using the shelving cart, how long before items are automatically marked as available in the stacks (hours)",
                    ),
                ],
                max_length=4,
            ),
        ),
    ]
