# Generated by Django 3.1.5 on 2021-02-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210207_0555"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uslocation",
            options={
                "verbose_name": "US Location",
                "verbose_name_plural": "US Locations",
            },
        ),
    ]
