# Generated by Django 3.1.5 on 2021-06-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alexandriauser_is_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alexandriauser",
            name="card_number",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
