# Generated by Django 3.1.5 on 2021-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210703_0404"),
    ]

    operations = [
        migrations.AddField(
            model_name="alexandriauser",
            name="host",
            field=models.CharField(default="default", max_length=100),
        ),
        migrations.AddField(
            model_name="branchlocation",
            name="host",
            field=models.CharField(default="default", max_length=100),
        ),
        migrations.AddField(
            model_name="uslocation",
            name="host",
            field=models.CharField(default="default", max_length=100),
        ),
    ]
