# Generated by Django 3.2.8 on 2021-10-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20210703_0503"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchlocation",
            name="open_to_public",
            field=models.BooleanField(
                default=True,
                help_text="Set to false if this building is staff-only or a processing center.",
                verbose_name="open to public",
            ),
        ),
    ]
