# Generated by Django 3.2.8 on 2021-10-26 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_branchlocation_open_to_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="alexandriauser",
            name="default_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.branchlocation",
            ),
        ),
    ]
