# Generated by Django 3.2.8 on 2021-11-15 17:04

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alexandriauser_default_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uslocation",
            name="state",
            field=localflavor.us.models.USStateField(
                blank=True, max_length=2, null=True, verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="uslocation",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(
                blank=True, max_length=10, null=True, verbose_name="Zip Code"
            ),
        ),
    ]
