# Generated by Django 3.2.9 on 2021-11-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alexandriauser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='alexandriauser',
            name='searchable_first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='alexandriauser',
            name='searchable_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
