# Generated by Django 4.0 on 2022-01-02 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20211121_0642"),
    ]

    operations = [
        migrations.AddField(
            model_name="alexandriauser",
            name="work_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_location",
                to="users.branchlocation",
            ),
        ),
        migrations.AlterField(
            model_name="alexandriauser",
            name="default_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_branch",
                to="users.branchlocation",
            ),
        ),
    ]
