# Generated by Django 4.0 on 2022-01-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alexandriauser_work_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alexandriauser",
            old_name="work_location",
            new_name="work_branch",
        ),
    ]
