# Generated by Django 3.1.5 on 2021-03-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holds", "0002_hold_pull_any_same_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hold",
            name="destination",
        ),
    ]
