# Generated by Django 3.1.5 on 2021-03-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holds", "0004_hold_destination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hold",
            name="pull_any_same_type",
        ),
    ]
