# Generated by Django 3.1.5 on 2021-03-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_record_summary"),
        ("holds", "0005_remove_hold_pull_any_same_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hold",
            name="requested_item_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.itemtype",
            ),
        ),
    ]
