# Generated by Django 3.2.8 on 2021-10-26 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alexandriauser_default_branch'),
        ('holds', '0008_hold_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.branchlocation'),
        ),
    ]
