# Generated by Django 3.2.8 on 2021-10-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holds', '0010_hold_specific_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hold',
            name='requested_item_type',
        ),
    ]
