# Generated by Django 3.2.8 on 2021-10-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holds', '0011_remove_hold_requested_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hold',
            name='record',
        ),
    ]
