# Generated by Django 3.2.8 on 2021-11-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holds', '0012_remove_hold_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='hold',
            name='force_next_available',
            field=models.BooleanField(default=False, help_text='Very rarely, certain holds need to be completed ahead of others. Setting this makes this hold be processed next, no matter where it is in the queue. If there are multiple holds with this flag, then they will be processed in order of oldest first.'),
        ),
    ]
