# Generated by Django 4.0.1 on 2022-01-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('_itemtype_checkout_limits', models.JSONField(default={}, verbose_name='itemtype checkout limits')),
                ('_itemtype_hold_limits', models.JSONField(default={}, verbose_name='itemtype hold limits')),
                ('checkout_limit', models.IntegerField(blank=True, default=150, help_text='How many materials total is this account type allowed to have checked out?', null=True, verbose_name='checkout limit')),
                ('hold_limit', models.IntegerField(blank=True, default=10, help_text='How many active holds is this account type allowed to have?', null=True, verbose_name='hold limit')),
                ('can_checkout_materials', models.BooleanField(default=True, help_text='Allow this account type to check out materials at all.')),
                ('allowed_item_types', models.ManyToManyField(help_text='This account type will only be allowed to check out the listed item types here. If this is empty, all item types will be allowed. Use the "Can Checkout Materials" toggle to disable all checkouts.', to='records.ItemType')),
            ],
        ),
    ]
