# Generated by Django 4.0.1 on 2022-01-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='_itemtype_checkout_limits',
            field=models.JSONField(default=dict, verbose_name='itemtype checkout limits'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='_itemtype_hold_limits',
            field=models.JSONField(default=dict, verbose_name='itemtype hold limits'),
        ),
    ]
