# Generated by Django 4.0.4 on 2022-05-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_searchable_chosen_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_money",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
