# Generated by Django 4.0.4 on 2022-05-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_saved_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="saved_money",
            field=models.IntegerField(default=0),
        ),
    ]
