# Generated by Django 4.0.5 on 2022-06-13 02:52

import django.db.models.deletion
from django.db import migrations, models

import alexandria.distributed.models


class Migration(migrations.Migration):

    dependencies = [
        ("distributed", "0001_initial"),
        ("users", "0005_alter_user_saved_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttype",
            name="host",
            field=models.ForeignKey(
                default=alexandria.distributed.models.Domain.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to="distributed.domain",
            ),
        ),
        migrations.AlterField(
            model_name="branchlocation",
            name="host",
            field=models.ForeignKey(
                default=alexandria.distributed.models.Domain.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to="distributed.domain",
            ),
        ),
        migrations.AlterField(
            model_name="uslocation",
            name="host",
            field=models.ForeignKey(
                default=alexandria.distributed.models.Domain.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to="distributed.domain",
            ),
        ),
    ]
