# Generated by Django 4.0.5 on 2022-06-13 04:27

import alexandria.distributed.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("distributed", "0001_initial"),
        ("users", "0006_alter_accounttype_host_alter_branchlocation_host_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="host",
            field=models.ForeignKey(
                default=alexandria.distributed.models.Domain.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                to="distributed.domain",
            ),
        ),
    ]
