# Generated by Django 4.0.2 on 2022-04-21 23:53

import alexandria.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_accounttype_options_remove_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.ForeignKey(
                on_delete=models.SET(alexandria.users.models.get_default_accounttype),
                to="users.accounttype",
            ),
        ),
    ]
