# Generated by Django 4.0.2 on 2022-04-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_accounttype_host_alter_accounttype_hold_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
