# Generated by Django 3.1.5 on 2021-02-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_item_bibliographic_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
