# Generated by Django 3.1.5 on 2021-02-07 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("catalog", "0003_auto_20210207_0619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
