# Generated by Django 3.1.5 on 2021-02-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('catalog', '0004_auto_20210207_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('branchlocation', 'alexandriauser')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
