# Generated by Django 3.1.5 on 2021-02-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_record_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="type",
        ),
        migrations.AlterField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this piece of media is counted as part of the collection.",
                verbose_name="active",
            ),
        ),
    ]
