# Generated by Django 3.1.5 on 2021-02-12 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_auto_20210212_0156"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.itemtype",
            ),
        ),
    ]
