# Generated by Django 3.1.5 on 2021-02-18 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_auto_20210218_0146"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="bibliographic_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.bibliographiclevel",
            ),
        ),
    ]
