# Generated by Django 3.1.5 on 2021-05-24 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_record_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name="due_date"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="renewal_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="itemtype",
            name="number_of_allowed_renews",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="itemtype",
            name="number_of_days_per_checkout",
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name="itemtypebase",
            name="name",
            field=models.CharField(
                choices=[
                    ("a", "Language material"),
                    ("c", "Notated music"),
                    ("d", "Manuscript notated music"),
                    ("e", "Cartographic material"),
                    ("f", "Manuscript cartographic material"),
                    ("g", "Projected medium"),
                    ("i", "Nonmusical sound recording"),
                    ("j", "Musical sound recording"),
                    ("k", "Two-dimensional nonprojectable graphic"),
                    ("m", "Computer file"),
                    ("o", "Kit"),
                    ("p", "Mixed materials"),
                    ("r", "Three dimensional artifact or naturally occurring object"),
                    ("t", "Manuscript language material"),
                ],
                max_length=1,
            ),
        ),
    ]
