# Generated by Django 3.1.5 on 2021-06-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210524_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='barcode'),
        ),
    ]
