# Generated by Django 3.1.5 on 2021-06-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_auto_20210629_0405"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="call_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="call_number"
            ),
        ),
    ]
