# Generated by Django 3.2.8 on 2021-10-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_itemtype_icon_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="icon_svg",
            field=models.TextField(blank=True, null=True),
        ),
    ]
