# Generated by Django 3.2.8 on 2021-10-31 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_itemtype_icon_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
