# Generated by Django 3.2.8 on 2021-11-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_auto_20211104_0033"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="number_of_concurrent_checkouts",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="itemtype",
            name="icon_svg",
            field=models.TextField(
                blank=True,
                help_text='Don\'t have a matching option in the Material Design icons? Copy the full SVG html here to display that instead. WARNING: must be fully formed SVG element; it will not be saved otherwise. Make sure that your `path` tag has `fill="currentColor"` in it so that colors work correctly and ensure that it displays well as 36px by 36px.',
                null=True,
                verbose_name="icon svg",
            ),
        ),
    ]
