# Generated by Django 3.2.8 on 2021-11-08 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20211105_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_checked_out',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='last_checked_out'),
        ),
    ]
