# Generated by Django 3.2.8 on 2021-11-08 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_item_last_checked_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_checked_out',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='last_checked_out'),
        ),
    ]
