# Generated by Django 3.2.9 on 2021-11-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_item_last_checked_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('check_in', 'Can check in materials'), ('check_out', 'Can check out materials')]},
        ),
    ]
