# Generated by Django 3.2.9 on 2021-11-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='searchable_authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='searchable_subtitle',
            field=models.CharField(blank=True, max_length=26021, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='searchable_title',
            field=models.CharField(default='', max_length=26021),
            preserve_default=False,
        ),
    ]
