# Generated by Django 3.2.9 on 2021-11-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20211121_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='searchable_uniform_title',
            field=models.CharField(blank=True, max_length=26021, null=True),
        ),
    ]
