# Generated by Django 3.1.5 on 2021-02-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_form', models.CharField(blank=True, choices=[('datas', 'Dataset (digital content intended for processing)'), ('img', 'Image'), ('mvemt', 'Movement (content expressed through motion, i.e. dance)'), ('music', 'Music'), ('objct', 'Object (a physical, 3D object)'), ('progm', 'Program (software)'), ('sound', 'Sounds (sound effects, animal noises, etc.)'), ('spknw', 'Spoken Word'), ('text', 'Text'), ('mcf', 'Multiple Content Forms (three or more terms apply)'), ('ocf', 'Other Content Form')], default='text', help_text="What is this media? Select 'Multiple Media' if three or more types describe this media.", max_length=5, null=True)),
                ('content_qualification', models.CharField(blank=True, choices=[('carto', 'Cartographic'), ('notat', 'Notated'), ('perfo', 'Performed')], help_text='Optional', max_length=5, null=True)),
                ('sensory_type', models.CharField(blank=True, choices=[('aural', 'Aural'), ('gusta', 'Gustatory'), ('olfac', 'Olfactory'), ('tacti', 'Tactile'), ('visua', 'Visual')], help_text='Optional', max_length=5, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('unmed', 'Unmediated'), ('audio', 'Audio'), ('elect', 'Electronic'), ('micfm', 'Microform'), ('micsp', 'Microscopic'), ('proje', 'Projected'), ('stero', 'Stereographic'), ('video', 'Video'), ('multm', 'Multiple Media'), ('othmd', 'Other Media')], default='unmed', help_text='Optional', max_length=5, null=True)),
                ('dimensionality', models.CharField(blank=True, choices=[('2d', '2-Dimensional'), ('3d', '3-Dimensional')], help_text='Optional -- image only', max_length=5, null=True)),
                ('motion_type', models.CharField(blank=True, choices=[('mvg', 'Moving'), ('still', 'Still')], help_text='Optional -- image only', max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentTypeManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ISBDRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_proper', models.TextField(blank=True, null=True)),
                ('title_parallel', models.TextField(blank=True, null=True)),
                ('title_information', models.TextField(blank=True, null=True)),
                ('title_statement_of_responsibility', models.TextField()),
                ('edition', models.TextField(blank=True, null=True)),
                ('specific_info', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('material_description', models.TextField(blank=True, null=True)),
                ('series', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resource_identifier', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, verbose_name='barcode')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('fine', 'Fine'), ('vygd', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='new', max_length=4, null=True, verbose_name='condition')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this piece of media is counted as part of the collection.', verbose_name='active')),
                ('object_id', models.PositiveIntegerField()),
                ('call_number', models.CharField(max_length=100, unique=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
