# Generated by Django 3.1.5 on 2021-02-01 04:54

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('users', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='home_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branchlocation'),
        ),
        migrations.AddField(
            model_name='media',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.isbdrecord'),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.ManyToManyField(related_name='content_type', to='media.ContentTypeManager'),
        ),
        migrations.AddField(
            model_name='isbdrecord',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='contenttypemanager',
            name='primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_content_type', to='media.contenttype'),
        ),
        migrations.AddField(
            model_name='contenttypemanager',
            name='secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_content_type', to='media.contenttype'),
        ),
    ]
