name: Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
    - name: Install Dependencies
      run: |
        sudo apt-get install libjpeg8 libjpeg-dev libpng-dev libpq-dev -y
        poetry install
    - name: Run Tests
      run: |
        poetry run pytest
